---
- name: Running show commands on Cisco IOS
  hosts: nxos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Run multiple commands on Cisco IOS nodes
      ios_command: #ansible module
        commands: #commands to run
          - show version
          - show ip interface brief
          - show run interface eth1/1

      #register: output    #register the output in a variable named output
      register: my_config    #register the output in a variable named output


    #-  debug: var=output.stdout_lines   #print the variable at the console line by line
    - name: Save output to file
      copy:
        content: "{{ my_config.stdout[0]}}"
        dest: "/root/Documents/ansible_playbook/ansible{{inventory_hostname}}.txt"

...


# Description:
# Run show commands using ios_command module
# http://docs.ansible.com/ansible/latest/ios_command_module.html

# Command to run:
# ansible-playbook -i ./hosts ./ios_command.yaml -u u1 -k
# both hosts and yaml file are in the current working directory